### ISSUE TITLE
some exercises

### ISSUE THREAD

**Issue by ketancmaheshwari** [barrymoo/sam-fall-tutorial#4]
Assuming that a file’s current permissions are rw-r-xr--, specify the
chmod expression required to change them to (i) rwxrwxrwx, (ii) r--r-----,
(iii) ---r--r-- , (iv) ---------.

Use find to locate from your home directory tree all (i) files with the extension
.html or .HTML,  (ii) directories having
permissions 666, (iii) files modified yesterday.

How do you extract the names of the users from /etc/passwd after ignoring the
first 4 entries?

**Comment by chiroptical** [comment]
Added.
